version: "3.8"
services:
    db:
        image: dmutoni/ebillingbackend:lastest
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "3306:3306"
    web:
      image: dmutoni/ebillingfrontend:latest  
      tty: true
      stdin_open: true
      build:
          context: frontend
          dockerfile: Dockerfile
    api:
      image: dmutoni/ebillingapi:latest
      tty: true
      stdin_open: true
      build:
          context: backend
          dockerfile: Dockerfile
    nginx:
      image: dmutoni/nginx:latest
      build:
          context:  ngnix
          dockerfile: Dockerfile
      ports:
            - "80:80"